custom domain name
sourcefuse/typescript-lambda-boilerplate pull request #71
Opened 2023-01-20 11:41 UTC by saurabhjindal-SF

2023-01-25 14:05 UTC, jamescrowley321 approved these changes

2023-01-25 14:15 UTC, jamescrowley321 requested changes

2023-01-25 14:15 UTC, jamescrowley321 commented on sourceloop-lambda/authentication-service-lambda/cdk/lambda/main.ts
> +    domainName: 'sl-auth-lambda.sfrefarch.com',
This value should not be hardcoded.

2023-01-25 17:16 UTC, tsaucier-sf approved these changes

2023-01-27 13:49 UTC, tsaucier-sf approved these changes

2023-01-30 16:39 UTC, jamescrowley321 approved these changes

2023-01-30 16:39 UTC, merged